### ISSUE TITLE
Breaks weirdly without Redis

### ISSUE THREAD

**Issue by danudey** [andrearaponi/dito#1]
Maybe this is against the entire point of this project; if so, I get it, fair enough.

I tried to get this running without a local Redis server, just to see how it worked; I disabled the auth, cache, and ratelimit middlewares (so nothing using Redis) and set `enabled: false` in the redis block, but making requests through the proxy gave me `runtime error: invalid memory address or nil pointer dereference`.

I assume that the assumption is that you don't want to run dito without a Redis server (given that it's hard-coded to require a Redis client from the ground up), but if you don't give it one it misbehaves rather than giving an explanatory error message.

This is the stack trace I got:

```
Oct  9 14:23:22.921 INF 👉 Dito it's ready on port: 8081
2024/10/09 14:23:36 http: panic serving [::1]:59534: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1()
	/path/to/golang/1.23.1/go/src/net/http/server.go:1947 +0xbe
panic({0x77d660?, 0xad0900?})
	/path/to/golang/1.23.1/go/src/runtime/panic.go:785 +0x132
dito/middlewares.CacheMiddleware.func1({0x895530, 0xc000148380}, 0xc00016a3c0)
	/tmp/dito/middlewares/cache_redis.go:38 +0x138
net/http.HandlerFunc.ServeHTTP(0x8928e0?, {0x895530?, 0xc000148380?}, 0x100000000000001?)
	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
dito/handlers.DynamicProxyHandler.LoggingMiddleware.func2({0x895530, 0xc000148340}, 0xc00016a3c0)
	/tmp/dito/middlewares/logging.go:34 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc0000148b0?, {0x895530?, 0xc000148340?}, 0xc00002a510?)
	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
dito/handlers.DynamicProxyHandler(0xc0000af740, {0x895620, 0xc00017a000}, 0xc00016a3c0)
	/tmp/dito/handlers/handlers.go:58 +0x33f
main.StartServer.func1({0x895620?, 0xc00017a000?}, 0xc0000e1b38?)
	/tmp/dito/cmd/main.go:73 +0x2d
net/http.HandlerFunc.ServeHTTP(0xc0000f8178?, {0x895620?, 0xc00017a000?}, 0x6ef5b6?)
	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x466f39?, {0x895620, 0xc00017a000}, 0xc00016a3c0)
	/path/to/golang/1.23.1/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc000122300?}, {0x895620?, 0xc00017a000?}, 0x6?)
	/path/to/golang/1.23.1/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00012c090, {0x895e48, 0xc0000afa10})
	/path/to/golang/1.23.1/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
	/path/to/golang/1.23.1/go/src/net/http/server.go:3360 +0x485
```

**Comment by andrearaponi** [comment]
> Maybe this is against the entire point of this project; if so, I get it, fair enough.
> 
> I tried to get this running without a local Redis server, just to see how it worked; I disabled the auth, cache, and ratelimit middlewares (so nothing using Redis) and set `enabled: false` in the redis block, but making requests through the proxy gave me `runtime error: invalid memory address or nil pointer dereference`.
> 
> I assume that the assumption is that you don't want to run dito without a Redis server (given that it's hard-coded to require a Redis client from the ground up), but if you don't give it one it misbehaves rather than giving an explanatory error message.
> 
> This is the stack trace I got:
> 
> ```
> Oct  9 14:23:22.921 INF 👉 Dito it's ready on port: 8081
> 2024/10/09 14:23:36 http: panic serving [::1]:59534: runtime error: invalid memory address or nil pointer dereference
> goroutine 18 [running]:
> net/http.(*conn).serve.func1()
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:1947 +0xbe
> panic({0x77d660?, 0xad0900?})
> 	/path/to/golang/1.23.1/go/src/runtime/panic.go:785 +0x132
> dito/middlewares.CacheMiddleware.func1({0x895530, 0xc000148380}, 0xc00016a3c0)
> 	/tmp/dito/middlewares/cache_redis.go:38 +0x138
> net/http.HandlerFunc.ServeHTTP(0x8928e0?, {0x895530?, 0xc000148380?}, 0x100000000000001?)
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
> dito/handlers.DynamicProxyHandler.LoggingMiddleware.func2({0x895530, 0xc000148340}, 0xc00016a3c0)
> 	/tmp/dito/middlewares/logging.go:34 +0x10a
> net/http.HandlerFunc.ServeHTTP(0xc0000148b0?, {0x895530?, 0xc000148340?}, 0xc00002a510?)
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
> dito/handlers.DynamicProxyHandler(0xc0000af740, {0x895620, 0xc00017a000}, 0xc00016a3c0)
> 	/tmp/dito/handlers/handlers.go:58 +0x33f
> main.StartServer.func1({0x895620?, 0xc00017a000?}, 0xc0000e1b38?)
> 	/tmp/dito/cmd/main.go:73 +0x2d
> net/http.HandlerFunc.ServeHTTP(0xc0000f8178?, {0x895620?, 0xc00017a000?}, 0x6ef5b6?)
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:2220 +0x29
> net/http.(*ServeMux).ServeHTTP(0x466f39?, {0x895620, 0xc00017a000}, 0xc00016a3c0)
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:2747 +0x1ca
> net/http.serverHandler.ServeHTTP({0xc000122300?}, {0x895620?, 0xc00017a000?}, 0x6?)
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:3210 +0x8e
> net/http.(*conn).serve(0xc00012c090, {0x895e48, 0xc0000afa10})
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:2092 +0x5d0
> created by net/http.(*Server).Serve in goroutine 1
> 	/path/to/golang/1.23.1/go/src/net/http/server.go:3360 +0x485
> ```

Hi Daniel,

Thank you for your feedback, but I was unable to replicate your error. Could you please attach your config.yaml?

Thank you :)
